import dynamic from 'next/dynamic';

export const register_pages: any = {
    default: dynamic(() => import('@/components/register/register-eleven')),
    one: dynamic(() => import('@/components/register/register-one')),
    two: dynamic(() => import('@/components/register/register-four')),
    three: dynamic(() => import('@/components/register/register-four')),
    four: dynamic(() => import('@/components/register/register-four')),
    five: dynamic(() => import('@/components/register/register-five')),
    seven: dynamic(() => import('@/components/register/register-seven')),
    eleven: dynamic(() => import('@/components/register/register-eleven')),
    fourteen: dynamic(() => import('@/components/register/register-seven')),
    fifteen: dynamic(() => import('@/components/register/register-seven')),
    sixteen: dynamic(() => import('@/components/register/register-four')),
    seventeen: dynamic(() => import('@/components/register/register-four')),
    eighteen: dynamic(() => import('@/components/register/register-five')),
    nineteen: dynamic(() => import('@/components/register/register-seven')),
    twenty: dynamic(() => import('@/components/register/register-seven')),
    twentyone: dynamic(() => import('@/components/register/register-four')),
    twentytwo: dynamic(() => import('@/components/register/register-four')),
    twentythree: dynamic(() => import('@/components/register/register-four')),
    twentyfour: dynamic(() => import('@/components/register/register-four')),
    twentyfive: dynamic(() => import('@/components/register/register-seven')),
    twentysix: dynamic(() => import('@/components/register/register-seven')),
    twentyseven: dynamic(() => import('@/components/register/register-four')),
    twentyeight: dynamic(() => import('@/components/register/register-four')),
    twentynine: dynamic(() => import('@/components/register/register-four')),
    thirty: dynamic(() => import('@/components/register/register-four')),
    thirtyone: dynamic(() => import('@/components/register/register-four')),
    thirtythree: dynamic(() => import('@/components/register/register-four')),
    thirtyfour: dynamic(() => import('@/components/register/register-five')),
    thirtyfive: dynamic(() => import('@/components/register/register-five')),
};
