import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
// import NextTopLoader from "nextjs-toploader";
import Announcement from '@/components/Announcement';
import getDesign from '@/utils/fetcher/getDesign';
import AppWrapper from './AppWrapper';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const design = await getDesign();
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {/* <NextTopLoader /> */}
                <Announcement design={design}/>
                <AppWrapper design={design}>{children}</AppWrapper>
            </body>
        </html>
    );
}
