'use client';

import dynamic from 'next/dynamic';

export const feature_products: any = {
    default: dynamic( () =>import('@/components/_homepage/feature-product/feature-product-seven')),
    two: dynamic(() => import('@/components/_homepage/feature-product/feature-product-four')),
    four: dynamic(() => import('@/components/_homepage/feature-product/feature-product-four')),
    five: dynamic(() => import('@/components/_homepage/feature-product/feature-product-five')),
    six: dynamic(() => import('@/components/_homepage/feature-product/feature-product-six')),
    seven: dynamic(() => import('@/components/_homepage/feature-product/feature-product-seven')),
    nine: dynamic(() => import('@/components/_homepage/feature-product/feature-product-nine')),
    eleven: dynamic(() => import('@/components/_homepage/feature-product/feature-product-eleven')),
    twelve: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twelve')),
    thirteen: dynamic(() => import('@/components/_homepage/feature-product/feature-product-thirteen')),
    sixteen: dynamic(() => import('@/components/_homepage/feature-product/feature-product-sixteen')),
    seventeen: dynamic(() => import('@/components/_homepage/feature-product/feature-product-seventeen')),
    eighteen: dynamic(() => import('@/components/_homepage/feature-product/feature-product-eighteen')),
    nineteen: dynamic(() => import('@/components/_homepage/feature-product/feature-product-nineteen')),
    twenty: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twenty')),
    twentyone: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twentyone')),
    twentytwo: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twentytwo')),
    twentythree: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twentythree')),
    twentyfour: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twentyfour')),
    twentyfive: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twentyfive')),
    twentysix: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twentysix')),
    twentyseven: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twentyseven')),
    twentyeight: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twentyeight')),
    twentynine: dynamic(() => import('@/components/_homepage/feature-product/feature-product-twentynine')),
    thirty: dynamic(() => import('@/components/_homepage/feature-product/feature-product-thirty')),
    thirtyone: dynamic(() => import('@/components/_homepage/feature-product/feature-product-thirty')),
    thirtythree: dynamic(() => import('@/components/_homepage/feature-product/feature-product-thirtythree')),
    thirtyfour: dynamic(() => import('@/components/_homepage/feature-product/feature-product-thirtyfour')),
    thirtyfive: dynamic(() => import('@/components/_homepage/feature-product/feature-product-thirtyfive')),
    thirtysix: dynamic(() => import('@/components/_homepage/feature-product/feature-product-thirtysix')),
    thirtyseven: dynamic(() => import('@/components/_homepage/feature-product/feature-product-thirtyseven')),
    thirtyeight: dynamic(() => import('@/components/_homepage/feature-product/feature-product-thirtyeight')),
    thirtynine: dynamic(() => import('@/components/_homepage/feature-product/feature-product-thirtynine')),
};
