import dynamic from "next/dynamic";

export const verify_otp_pages: any = {
  default: dynamic(() => import("@/components/otp/verify-otp-eleven")),
  one: dynamic(() => import("@/components/otp/verify-otp-one")),
  two: dynamic(() => import("@/components/otp/verify-otp-four")),
  three: dynamic(() => import("@/components/otp/verify-otp-four")),
  four: dynamic(() => import("@/components/otp/verify-otp-four")),
  five: dynamic(() => import("@/components/otp/verify-otp-five")),
  seven: dynamic(() => import("@/components/otp/verify-otp-seven")),
  eleven: dynamic(() => import("@/components/otp/verify-otp-eleven")),
  fourteen: dynamic(() => import("@/components/otp/verify-otp-seven")),
  fifteen: dynamic(() => import("@/components/otp/verify-otp-seven")),
  sixteen: dynamic(() => import("@/components/otp/verify-otp-four")),
  seventeen: dynamic(() => import("@/components/otp/verify-otp-four")),
  eighteen: dynamic(() => import("@/components/otp/verify-otp-five")),
  nineteen: dynamic(() => import("@/components/otp/verify-otp-seven")),
  twenty: dynamic(() => import("@/components/otp/verify-otp-seven")),
  twentyone: dynamic(() => import("@/components/otp/verify-otp-four")),
  twentytwo: dynamic(() => import("@/components/otp/verify-otp-twentyone")),
  twentythree: dynamic(() => import("@/components/otp/verify-otp-twentyone")),
  twentyfour: dynamic(() => import("@/components/otp/verify-otp-four")),
  twentyfive: dynamic(() => import("@/components/otp/verify-otp-seven")),
  twentysix: dynamic(() => import("@/components/otp/verify-otp-four")),
  twentyseven: dynamic(() => import("@/components/otp/verify-otp-four")),
  twentyeight: dynamic(() => import("@/components/otp/verify-otp-four")),
  twentynine: dynamic(() => import("@/components/otp/verify-otp-four")),
  thirty: dynamic(() => import("@/components/otp/verify-otp-four")),
  thirtyone: dynamic(() => import("@/components/otp/verify-otp-four")),
  thirtythree: dynamic(() => import("@/components/otp/verify-otp-four")),
  thirtyfour: dynamic(() => import("@/components/otp/verify-otp-four")),
  thirtyfive: dynamic(() => import("@/components/otp/verify-otp-four")),
};

